name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs once every 24 hours

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Create dummy grades.json if not exists
      run: |
        if [ ! -f grades.json ]; then
          echo '[]' > grades.json
        elif [ ! -s grades.json ]; then
          echo '[]' > grades.json
        fi

    - name: Run script to update README
      run: |
        python update_readme.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update README with latest grades'
        file_pattern: README.md